version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/root/nginx/certbot/conf:/home/root/nginx/certbot/conf:ro
      - ./certbot/www:/var/www/certbot
    networks:
      - photogo-network
    restart: always

networks:
  photogo-network:
    external: true
