name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Chạy pipeline khi có push vào nhánh 'main'
  pull_request:
    branches:
      - main  # Chạy pipeline khi có pull request vào nhánh 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Kiểm tra mã nguồn từ GitHub
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Đăng nhập vào DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker image và push lên Docker Hub
      - name: Build and push Docker image
        run: |
          docker build --platform linux/amd64 -t photogo-nextjs:latest .
          docker tag photogo-nextjs:latest photogo/photogo-nextjs:latest
          docker push photogo/photogo-nextjs:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production

    steps:
      # Step 1: Kiểm tra mã nguồn từ GitHub
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Đăng nhập vào VPS và deploy ứng dụng
      - name: Deploy to VPS
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd /path/to/your/app &&
            docker-compose pull &&  # Pull image mới nhất từ Docker Hub
            docker-compose up -d  # Chạy lại container
          "
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
